### ISSUE TITLE
Dekker feedback

### ISSUE THREAD

**Issue by simultech** [deco3500/newsbias#1]
Very good problem space.  I like the idea, and educating the user is very important.  I like the idea of informing users, especially less informed audiences.  Look at the Crikey news bias graphs.  So many ways to present this.  I personally would love to see this as a Chrome Extension.

**Comment by lollyborch** [comment]
Thanks.  We're adding a Chrome Extension as a stretch goal and will look at the Crikey news bias graphs as part of our research for our next step.
