### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by tszlamchan** [deco3500/newsbias#10]
Hi Newsbias. Good job in the presentation. I think the idea is good. Users can comment below the news and vote are good ways to solve this problem I think. Users can also communicate with each other. However everyone has his or her opinion, the comments they made maybe biased too.

**Comment by lollyborch** [comment]
Thanks for your feedback. We're trying to make the crowd sourced opinion part of the app obvious that it is opinion based, not fact based so people can judge for themselves how much they pay attention to that.
