### ISSUE TITLE
Research Chrome Extension

### ISSUE THREAD

**Issue by lollyborch** [deco3500/newsbias#13]

**Comment by lollyborch** [comment]
user is on a news website or article
click extension
views information on the site
has a link to our website

**Comment by kirillmomo** [comment]
Reference for the google extension

https://www.youtube.com/watch?v=jyhu42WSC6Y&list=PLYxzS__5yYQlWil-vQ-y7NR902ovyq1Xi&index=1

**Comment by kirillmomo** [comment]
New function added, grab hostname from google chrome URL.
Added sliding bar

**Comment by kirillmomo** [comment]
Future function,
Link with the data, display rating.
