### ISSUE TITLE
Team Worldwide Critique

### ISSUE THREAD

**Issue by t-siri** [deco3500/newsbias#2]
Often people read news to just know and want to know information, sometimes they do not really pay attention to the bias of the news. 

My question here is that what if it is not engaging enough as most people do not really find much interest on who owns the news - even if they do know they might not care as much(?)

I really like the concept and idea of your application, I just find that the content that you return to the user is not as engaging enough and will not get users to want to constantly use your application

Maybe if you return more interesting data to users such as how many people read it, a poll of opinions towards a news article, how people have responded to the news. 
Also, once a user has used the application for a long amount of time, maybe have data being returned filtered data according to what users are more interested in retrieving back from the application in order to save time.

Again great idea, I just feel that what is being returned might need to be worked on a bit more, as we all have different interests.

**Comment by lollyborch** [comment]
Thanks for the feedback, we're adding in more ways for users to engage by linking to social media and developing a chrome extension.
