### ISSUE TITLE
Initial design of search info presented

### ISSUE THREAD

**Issue by lollyborch** [deco3500/newsbias#25]

**Comment by lollyborch** [comment]
Inital search results done.  Need to decide on what data we will present before this can be completed.

**Comment by lollyborch** [comment]
-what sites we will include
-what info do we want to include

**Comment by chrispala** [comment]
I had an idea for this - ACMA has PDF snapshots for major entities that show quite a bit of information. There's one available for almost every media entity in the country, eg: http://www.acma.gov.au/webwr/media-ownership/ACMA_FairfaxMedia.pdf 
Could add the PDF URL in as part of the ownership then embed it on the search page using google docs PDF viewer or similar, e.g.:
`
<iframe src="http://docs.google.com/gview?url={insert url property here}&embedded=true" style="width:700px; height:500px;" frameborder="0"></iframe>`
I tried playing around with the index.html and controller.js files to test it out - it works, only issue is that it loads quite slowly.
