### ISSUE TITLE
Critiques on your concept

### ISSUE THREAD

**Issue by shiva007oct** [deco3500/newsbias#3]
**Who owns your news**
- how would you achieve what you want to achieve, could you run us through a scenario?
- Voting system is a good way to measure validation of news
- What is the motivation for the user in terms of participation and engagement ?

**Comment by lollyborch** [comment]
user participation is self-generated through desire to know more about bias.  we are adding in additional ways for users to interact by linking fact checking results to share on social media and developing a chrome extension.
