### ISSUE TITLE
Week 10 Meeting

### ISSUE THREAD

**Issue by lollyborch** [deco3500/newsbias#38]
To Discuss (everyone please add items here before Wed 5/10):
-what sites we will include
-what info do we want to include

**Comment by leoliuxu** [comment]
After testing, the index.html needs to be adjusted when narrow the browser and the content is out of container.
And yah, we need an IP validator like you mentioned.

I think we will mainly demonstrate the search function we've done so far which is functioning well and the rate section as well. The about page can be done before stand-up presentation, but any idea for about page to make it not such boring?
