### ISSUE TITLE
Feedback on concept

### ISSUE THREAD

**Issue by TrevH** [deco3500/newsbias#4]
Not sure of the concepts.  Are you analysing news or giving feedback on news?  Are you going to draw your news from Global or local news.
OK  . . . getting the idea of gauging opinion. 

Is there some sense of giving comments back and rating like Foresquare.  Is this able to then put the word out there that certain news sources are not reliable.  Where can you present these public recordings open to all to see.

great idea!

**Comment by lollyborch** [comment]
Our concept analyses news ownership and provides independent fact checking of individual news articles.  Our web app would be the platform where users could see all the ratings.  We are adding in additional connectivity by allowing users to share fact checking result to social media.
