### ISSUE TITLE
Decide on fact check criteria

### ISSUE THREAD

**Issue by lollyborch** [deco3500/newsbias#43]

**Comment by lollyborch** [comment]
Try by end of week 7 oct

**Comment by chrispala** [comment]
Hi @lollyborch, I've done some notes up on an article submission form / criteria for the fact checking process. I ended up just using the 4 questions from the proposal; we don't need to completely flesh that aspect out anyway.
I think we need a category field on the article submission form as not all kinds of news (e.g. Sport, Weather, Lifestyle, etc) are appropriate for the fact checking process.
Aware our remaining time is limited; not expecting we would implement anything necessarily - just wanted to try and get something down on how it "could" work to accompany some screenshots, etc.
https://drive.google.com/open?id=1h10mgCl437e2SpQN7ESBnBE9jH3SmnnHF2ZTz_YGAjw
