### ISSUE TITLE
Feedback on Concept

### ISSUE THREAD

**Issue by awaishameedkhan** [deco3500/newsbias#5]
I really like the concept of knowing who owns your news  - it reminded me of this image of companies that own everything: https://i.kinja-img.com/gawker-media/image/upload/s--jyv7x7Tb--/c_scale,fl_progressive,q_80,w_800/794701813831831470.jpg

but I think one aspect which needs to be made a bit more granular is maybe having if not a global regional cut for the purposes of this prototype, but look at a regional or provincial cut? QLD vs VIC vs WA etc. It may help users identify with localities and any biases that are native to those areas.
- Potentially in addition to your fact check review panel feature, maybe maintain a history of contributions of users and add a rating scale for the general contributors (like how you have one for eBay)

**Comment by lollyborch** [comment]
Thanks, the rating scale for contributors is interesting.  We were thinking of something similar to articles on the conversation where is lists where contributors receive funding and any known biases/conflict of interest (e.g. https://theconversation.com/students-are-not-hard-wired-to-learn-in-different-ways-we-need-to-stop-using-unproven-harmful-methods-63715)
