### ISSUE TITLE
concept critique - feedback control

### ISSUE THREAD

**Issue by dayrek** [deco3500/newsbias#6]
How will the public rating system be controled? There are quite a few methods to mess with internet polls outcomes, loging IPs to responses might be one way to deal with this.

Also public opinion is inherently biased, how will your application stop itself from having a political leaning due to this?

**Comment by lollyborch** [comment]
Thanks for the tip about loging IPs.  We will be making it really clear what is fact (i.e. this paper is owned by this company) and what is crowd-sourced opinion.  Hopefully users will take the opinion with a grain of salt.
