### ISSUE TITLE
Critique

### ISSUE THREAD

**Issue by ScriptSmith** [deco3500/newsbias#7]
- How are you getting people to submit links? Where do they come from? Copy-pasting can be a challenge. Does your idea within the context of a mobile application?
- How do you stop media companies from using your app and poisoning the results?

**Comment by lollyborch** [comment]
Thanks for the feedback.

We acknowledge that copy/paste is a bit clunky.  We've chosen a web-app to be device neutral but are also adding in a chrome extension to make it easier for users to check articles on the fly, on the website they are already reading from.

media companies could add to the crowd sourced rating but the main results that are returned are stored from a database with fact'based information (like who owns the news site) which can't eaily be scammed.
