### ISSUE TITLE
Hiu Fung Shum (Bryan) Team WorldWide  

### ISSUE THREAD

**Issue by bryanshum** [deco3500/newsbias#8]
Hi news bias,
I like your group's ideas especially your application is about the bias of the news! Your application is a good way to educate the users and let them understand the overview of the news. However, I cannot see that your application is engaging users and encourage interaction within the users. Users may not interested who own the news or have different opinion on the news, the quick way to solve these problems is allow users to choose the news that they want to read and let them compare with the other similar news but have different opinion on the same incident. 

Moreover,  you guys need to think about how to make people constantly use your application, how to make it more interesting such as make the interface more user friendly. Anyways, it's a great idea and good luck with it!

**Comment by lollyborch** [comment]
Thanks for your feedback.  we're looking at adding a chrome extension to help with engagement.
