### ISSUE TITLE
Critique

### ISSUE THREAD

**Issue by leehiulam** [deco3500/newsbias#9]
People don’t often pay attention to the bias in new many people believe on what they have been told so I really like your idea. However, having public opinion can let people discuss and think or even change their thought about the particular news article but sometimes people’s thoughts can be inherently biased. Also how is this application engage users to use it constantly? Maybe categories the news so user can discuss, vote and look at the news that they are interested.

**Comment by lollyborch** [comment]
Thanks for your feedback.  We're trying to make the crowd sourced opinion part of the app obvious that it is opinion based, not fact based so people can judge for themselves how much they pay attention to that.
